### ARTICLE CREATE
POST http://localhost:8080/api/v1/article/private
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM1MzIzNzEsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM2MTg3NzEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.X5SJjCxQeMHAdoY-8LHia22qpvNbGnAYIRQ2yTn6a95kwwnYhzvSAisYE_hEhs6mXpgrn-ifp3hFZWPGQ4aqGA
Content-Type: application/json

{
  "title": "1derere",
  "description": "regethrthrt",
  "content": "qwcwefref",
  "attachId": "10f3ba26-d714-4bc7-b26e-74cb9a76207c",
  "regionId": 1,
  "categoryId": 1,
  "articleTypeId": 3
}

### UPDATE BY ID
POST http://localhost:8080/api/v1/article/private/e84455a5-e5be-4352-aeb6-c5e699535c1d
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM1MzIzNzEsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODM2MTg3NzEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.X5SJjCxQeMHAdoY-8LHia22qpvNbGnAYIRQ2yTn6a95kwwnYhzvSAisYE_hEhs6mXpgrn-ifp3hFZWPGQ4aqGA
Content-Type: application/json

{
  "title": "Salom1"
}

### DELETE BY ID
DELETE http://localhost:8080/api/v1/article/1

### CHANGE STATUS
POST http://localhost:8080/api/v1/article/change-status/1

### GET 5 ARTICLE
GET http://localhost:8080/api/v1/article/getLast5Article/1

### GET 3 ARTICLE
GET http://localhost:8080/api/v1/article/getLast3Article/1

### GET 8 ARTICLE WITHOUT ARTICLE ID
POST http://localhost:8080/api/v1/article/getLast8Article/1
Content-Type: application/json

{
  "article_id": ["1", "2", "3"]
}

### GET BY ID
GET http://localhost:8080/api/v1/article/getById/51fc3e4b-c54b-409c-9423-0ce7c20c7fb2