### Article Type create
POST http://localhost:8080/api/v1/article-type/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI4NjI0OTEsImlkIjo5LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI5NDg4OTEsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.QjMmbCvTmv1yheNjdvNx-LhhthHtxLvRcPuYYJvwomki_UU6-Rhx4DPtuqMRNQ39R7qxxfc3CzsoLk1Te6DTBA
Content-Type: application/json

{
  "nameUz": "MUXARRIR TANLOVI",
  "nameRU": "MUXARRIR TANLOVI",
  "nameEng": "MUXARRIR TANLOVI"
}

### ArticleType update with id
PUT http://localhost:8080/api/v1/article-type/1
Content-Type: application/json

{
  "nameUz": "suv",
  "nameRU": "voda",
  "nameEng": "water"
}

###  ArticleTYpe delete with id
DELETE http://localhost:8080/api/v1/article-type/1

### ArticleType get all
GET http://localhost:8080/api/v1/article-type/list-paging

### Get by lang