### Region create
POST http://localhost:8080/api/v1/category/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NzE4NzksImlkIjo5LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4NTgyNzksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.rTSQUZb_ql0g8laDRPZcheqySvUMEElmtUG4zbtl8tYkYbijeNrm2bd4FkNaEoUaPd9NhxJaiDb_YCVRiZCbow
Content-Type: application/json

{
  "nameUz": "Audio",
  "nameRU": "Аудио",
  "nameEng": "Audio"
}

### Region update with id
PUT http://localhost:8080/api/v1/category/1
Content-Type: application/json

{
  "nameUz": "Radio",
  "nameRU": "Радио",
  "nameEng": "Radio"
}

###  Region delete with id
DELETE http://localhost:8080/api/v1/category/1

### Regionx get all
GET http://localhost:8080/api/v1/category/list-paging

### Get by lang