### Region create
POST http://localhost:8080/api/v1/region/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NzE4NzksImlkIjo5LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4NTgyNzksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.rTSQUZb_ql0g8laDRPZcheqySvUMEElmtUG4zbtl8tYkYbijeNrm2bd4FkNaEoUaPd9NhxJaiDb_YCVRiZCbow
Content-Type: application/json

{
  "nameUz": "Fargona",
  "nameRU": "Enisey",
  "nameEng": "Oxvord"
}

### Region update with id
PUT http://localhost:8080/api/v1/region/1
Content-Type: application/json

{
  "nameUz": "Andijon",
  "nameRU": "Russia",
  "nameEng": "England"
}

###  Region delete with id
DELETE http://localhost:8080/api/v1/region/3

### Regionx get all
GET http://localhost:8080/api/v1/region/list-paging

### Get by lang